# Generated by Django 4.1.7 on 2023-02-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formationsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='students',
            field=models.ManyToManyField(to='formationsApp.user'),
        ),
    ]
