# Generated by Django 4.1.7 on 2023-02-15 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formationsApp', '0002_session_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formations',
            name='trainer',
        ),
    ]
