# Generated by Django 4.1.7 on 2023-02-16 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formationsApp', '0004_delete_user_alter_session_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='formations',
            name='trainer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
